version: "3.8"

services:
  scraper:
    build: .
    container_name: tscrapper
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./my_user_session.session:/app/my_user_session.session
    environment:
      - HEALTH_PORT=8000
      - TZ=Europe/Moscow
    restart: unless-stopped
